### ISSUE TITLE
Typo in IIS URL ReWrite Article

### ISSUE THREAD

**Issue by mertozturk80** [MicrosoftDocs/iis-docs#1003]
I was following below article for configuring URL Rewrite. 

https://learn.microsoft.com/en-us/iis/extensions/url-rewrite-module/modifying-http-response-headers 

There is a typo in the article here, where the condition should be ORIGINAL_HOST, instead of ORIGINAL_URL , when configuration outbound rule. 

 
![image](https://github.com/MicrosoftDocs/iis-docs/assets/6884474/a5d699b5-d4f4-4ad2-a5a6-2579a987ee1f)

Also example does not use ARR at all, as indicated in the beginning but it only use the URL Rewrite. 

 
![image](https://github.com/MicrosoftDocs/iis-docs/assets/6884474/c0a8f323-9862-49a3-9b02-d4457924966c)

Could you review the article to fix these points?

**Comment by lextm** [comment]
I created a PR to address this typo. But I don't think the ARR part needs to be changed.
