### ISSUE TITLE
Very out of date article - requesting removal

### ISSUE THREAD

**Issue by dzsquared** [MicrosoftDocs/iis-docs#1023]
Hi!  PM over in Azure Data - the article at https://github.com/MicrosoftDocs/iis-docs/blob/main/iis/publish/using-web-deploy/dbdacfx-provider-for-incremental-database-publishing.md contains a lot of content about the DacFx library and web deploy that is extremely out of date.  While the integration between the 2 has been deprecated, there are also a lot of dated/incorrect statements in the article.
Can that article be removed, please?
```[tasklist]
### Tasks
```

**Comment by Rick-Anderson** [comment]
I'll remove it.
