### ISSUE TITLE
Example split into 3 separate code text boxes

### ISSUE THREAD

**Issue by NichlasNielsen** [MicrosoftDocs/iis-docs#1044]
Hello,

The code examples for this article is split into 3 separate code text boxes, it seems the intention was to only have 1 code text box with all the code inside:

![image](https://github.com/MicrosoftDocs/iis-docs/assets/97018784/279e0b59-4b6d-44d6-b091-c2d2fc4ed619)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a97ea8e4-915f-9ab1-2a42-8008f56f88d4
* Version Independent ID: 46db91d9-11fa-174a-8199-b8c7a402e4b7
* Content: [Application.ApplicationPoolName Property (Microsoft.Web.Administration)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.applicationpoolname?view=iis-dotnet)
* Content Source: [iis-dotnet/xml/Microsoft.Web.Administration/Application.xml](https://github.com/MicrosoftDocs/iis-dotnet-sdk-docs-pr/blob/live/iis-dotnet/xml/Microsoft.Web.Administration/Application.xml)
* Service: **iis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **soshir**

**Comment by NichlasNielsen** [comment]
It seems to have happened to all code samples, actually.

**Comment by NichlasNielsen** [comment]
Also appears here:

https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.applicationpoolname?view=iis-dotnet
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.enabledprotocols?view=iis-dotnet
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.path?view=iis-dotnet
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.virtualdirectories?view=iis-dotnet
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.virtualdirectorydefaults?view=iis-dotnet

**Comment by lextm** [comment]
Thanks for the report. However, those articles do not belong to this repo so cannot be fixed from here either.

Let me check if I can reach out to the actual owner of them.

**Comment by lextm** [comment]
After some digging I think you might repor this issue to [dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/issues) repo, because those pages fall under "IIS SDK for .NET" and are showed in .NET API browser,

https://learn.microsoft.com/en-us/dotnet/api/?view=iis-dotnet

> If you have any feedback, create a new issue in the [dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/issues) repo.

**Comment by wadepickett** [comment]
@NichlasNielsen, thanks very much for reporting the issue and for moving it to the API repo.
