### ISSUE TITLE
Updates needed for Powershell gallery download 

### ISSUE THREAD

**Issue by terrimorton** [MicrosoftDocs/iis-docs#105]
See comment at the bottom of this article:
https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/iisadministration-powershell-cmdlets

This article needs to be updated to reflect that the cmdlets are supported now via a Powershell gallery download on Windows 2012 R2 and up. https://blogs.iis.net/iisteam/introducing-iisadministration-in-the-powershell-gallery

Also, the Technet link on the article is broken.

**Comment by jhkimnew** [comment]
This is fixed now. The updated content will be available soon.
