### ISSUE TITLE
confirm patterning for wildcard-host-header-support

### ISSUE THREAD

**Issue by kirancheema** [MicrosoftDocs/iis-docs#112]
Hi It would be good to have some further examples of what is / isn't possible with the wild card patterns 

at the moment the example is *.contoso

Does it work (like apache) with the wild card anywhere e.g.  Example.*.contoso ? 

e.g will it capture service.client1.com & service.client2.com with the service.*.com pattern 

Before any one says why would you do it that way why wouldn't you do it as *.service.com
This is a real life example usage we have a single site that that switches templates / switches content depending on the URL that comes in. e.g. doc A & B is shown to service.client1.com and Doc A & C service.client2.com and is configured so that the site has a consistent look and feel to the clients own site and uses clients subdomain

**Comment by bariscaglar** [comment]
@kirancheema are you referring to CORS documentation or some other? iis-docs is a huge repository and wild cards are used in quite a few places.

**Comment by kirancheema** [comment]
Hi @bariscaglar 
thanks for the message 

It was the info on this page about wildcard host support that I was referring too: 
https://docs.microsoft.com/en-gb/iis/get-started/whats-new-in-iis-10/wildcard-host-header-support

**Comment by bariscaglar** [comment]
@jhkimnew can you take a look at this?

**Comment by jhkimnew** [comment]
The wild card can be used in subdomain only. For example, neither a.*.c nor *b.c are allowed. However, *.b.c and *.c are allowed.

@Shirhatti Would you please update https://docs.microsoft.com/en-gb/iis/get-started/whats-new-in-iis-10/wildcard-host-header-support ?

**Comment by bariscaglar** [comment]
@shirhatti ping on this.
