### ISSUE TITLE
HTML table no longer renders correctly on IIS 7.0 Features and Vista Editions

### ISSUE THREAD

**Issue by terrimorton** [MicrosoftDocs/iis-docs#121]
[https://docs.microsoft.com/en-us/iis/install/installing-iis-7/iis-features-and-vista-editions](https://docs.microsoft.com/en-us/iis/install/installing-iis-7/iis-features-and-vista-editions)

In May the "IIS 7.0 Vista Edition Feature Matrix" was rendering as a table (but the last few columns were not visible).  Today, the table is not rendering - it seems to be encoded instead. 

For comparison, the table at [https://docs.microsoft.com/en-us/iis/install/installing-iis-7/understanding-setup-in-iis](https://docs.microsoft.com/en-us/iis/install/installing-iis-7/understanding-setup-in-iis) is still rendering as a table.

Screenshot:
![2018-01-24_9-31-26](https://user-images.githubusercontent.com/4643903/35337507-699779c0-00e9-11e8-9ce5-679c09e263c8.jpg)

**Comment by bariscaglar** [comment]
#126 resolves this.
