### ISSUE TITLE
RS4?

### ISSUE THREAD

**Issue by sundarchi1** [MicrosoftDocs/iis-docs#124]
Windows 10 RS4 is getting closer - are we getting docs for what's new in IIS 10 RS4, or is there nothing new?

**Comment by bariscaglar** [comment]
We have a few exciting things we have done in the RS4 timeframe and we will try to advertise these on iis.net. They are all out of box, though. One of them is manage.iis.net monitoring features. This is already live. The other is support for Brotli compression; that should be ready closer to actual RS4 release. ASP.NET core module is also getting a big overhaul.

In-box changes to IIS RS4 are mainly bug fixes.

**Comment by sundarchi1** [comment]
@bariscaglar Thanks so much for the response. Sounds great!
Maybe put up a roadmap or something so we can get an idea what to expect with these more frequent semi-annual releases.

**Comment by sundarchi1** [comment]
@bariscaglar When do the Brotli and ASP.NET Core v2 modules release?

**Comment by bariscaglar** [comment]
@shirhatti for ANCM release date. Brotli should come out aligned with RS4 GA. Look for announcements on iis.net site.
