### ISSUE TITLE
bad link, to export file

### ISSUE THREAD

**Issue by californiaimage** [MicrosoftDocs/iis-docs#129]
Should be https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/export-a-package-through-iis-manager
Not reference to mail.microsoft.com

**Comment by bariscaglar** [comment]
Can you tell us what link you're referring to?

**Comment by terrimorton** [comment]
I found it, the bad link is on this page: [https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/import-a-package-through-iis-manager](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/import-a-package-through-iis-manager). (Export a Package through IIS Manager)

**Comment by bariscaglar** [comment]
@terrimorton is this something you can take care of?

**Comment by terrimorton** [comment]
Sure: [https://github.com/MicrosoftDocs/iis-docs/pull/138](https://github.com/MicrosoftDocs/iis-docs/pull/138)

**Comment by terrimorton** [comment]
@bariscaglar This issue is resolved and should be closed.

**Comment by terrimorton** [comment]
Looks good, thanks!

**Comment by terrimorton** [comment]
@alligreubel Are you able to close this ticket?

**Comment by alligreubel** [comment]
@terrimorton Unfortunately not, an admin/owner of this repo should be able to though!
