### ISSUE TITLE
onlyoffice with owncloud have some problem.

### ISSUE THREAD

**Issue by jianbosu** [MicrosoftDocs/iis-docs#146]
i setup a server  in lan by (https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud),  work well by LAN  
IP or hostname.

then i setup a reverse proxy by windows 2016 iis 10,all rules is the default rules. but some images can't display and the onlyoffice can't work  by access from internet

**Comment by bariscaglar** [comment]
@jianbosu what is your specific question/issue regarding IIS documentation? I am not familiar with OnlyOffice.

**Comment by bariscaglar** [comment]
Please feel free to reopen if you have more information on the subject.
