### ISSUE TITLE
Unnecessary backslash in AppCmd.exe command args

### ISSUE THREAD

**Issue by SIkebe** [MicrosoftDocs/iis-docs#150]
There is an unnecessary backslash between `/config:` and `*`.

https://docs.microsoft.com/en-us/iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe

![backslash](https://user-images.githubusercontent.com/17608272/39225775-3c46849c-4889-11e8-9e53-4283216950c2.png)

**Comment by SIkebe** [comment]
`**/config:\***` in markdown

**Comment by bariscaglar** [comment]
@SIkebe could you send a pull request to fix this?

**Comment by SIkebe** [comment]
@bariscaglar Sure, will do!
