### ISSUE TITLE
Need update system.webServer/security/requestFiltering/removeServerHeader attribute

### ISSUE THREAD

**Issue by chyonek** [MicrosoftDocs/iis-docs#186]
This document describes "IIS 10.0 added the removeServerHeader", but this attribute has no effect on some OS versions.

_IIS 10.0 added the removeServerHeader attribute to suppress sending the HTTP server header to remote clients._
**Request Filtering <requestFiltering>**
https://github.com/MicrosoftDocs/iis-docs/blob/master/iis/configuration/system.webServer/security/requestFiltering/index.md

I verified that attribute. It is effective for after 1709 (RS 3). It is not effective for 1607 (RS1) and 1703 (RS2). This is a bug.
Could you update that it supports on version 1709 or later?

**Comment by shirhatti** [comment]
Merged in 2f3954e2af7b1857bfe2ba2e9d3181c4e6192d31

**Comment by chyonek** [comment]
@shirhatti Thank you for your check.  When will [docs page](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/) be updated?
By the way, can you fix it as follows? I noticed that "was" was duplicated.

**before**
Note: This attribute **was was** added in IIS 10.0 and does not work in versions of Windows prior to Windows Server, version 1709 or Windows 10, version 1709.

**after**
Note: This attribute **was** added in IIS 10.0 and does not work in versions of Windows prior to Windows Server, version 1709 or Windows 10, version 1709.
