### ISSUE TITLE
Web Deploy 4.0?

### ISSUE THREAD

**Issue by EatonZ** [MicrosoftDocs/iis-docs#195]
The latest Visual Studio 2017 comes with Web Deploy 4.0. The latest version documented and published is 3.6.
I think some documentation on what's new would be helpful.

I tracked down the installer to [this link](https://download.visualstudio.microsoft.com/download/pr/e1828da1-907a-46fe-a3cf-f3b9ea1c485c/035860f3c0d2bab0458e634685648385/webdeploy_amd64_en-us.msi), is it safe to use on production servers?

**Comment by shirhatti** [comment]
FYI @honggit. We need to publish updated WebDeploy binaries to DLC.

**Comment by EatonZ** [comment]
@shirhatti @HongGit Is this up yet?

**Comment by shirhatti** [comment]
@EatonZ Unfortunately, we're still working through an issue where when folks have already installed version of WebDeploy with higher version than that in Visual Studio, it causes VS install to fail. As such thus far we've limiting WebDeploy 4.0 to Visual Studio only and are trying approaches to fix the WebDeploy installer.

We hope to have an update soon

**Comment by EatonZ** [comment]
@shirhatti Still working through the issue?

**Comment by KriNiTo** [comment]
Is it fixed or planned to fix? Is there an target date?

**Comment by NeskireDK** [comment]
Still no changelog? That quite concerning. 
I simply want to answer the question if 3.6 is capable of publishing asp.net 4.8

**Comment by EatonZ** [comment]
I feel like IIS work the past year has been focused elsewhere - maybe .NET core. [IIS 1809 release notes](https://github.com/MicrosoftDocs/iis-docs/pull/215), for example, still haven't been merged yet.

On this topic, I asked @shirhatti [on Twitter a while ago for a changelog](https://twitter.com/XeEaton/status/1154173697491709954), but no response.

**Comment by bariscaglar** [comment]
The comment I got from the engineer who upgraded Web Deploy to 4.0 is this:

"The biggest change from v3.6 to v4.0 is the change of the target framework: .NET v3.5 to v4.5. Other than that, there are bug fixes that don’t impact the end users directly".

**Comment by bariscaglar** [comment]
Please reopen if this does not answer your question. Thank you!

**Comment by sujitnayak** [comment]
The major change in WebDeploy 4.0 is that it is built against .NET 4.5 instead of .NET 3.5. No new features have been added other than some bug fixes. Currently WebDeploy 4.0 is only available with Visual Studio 2017 and higher. There are no plans to make it available through download center. 

If you need to acquire the WebDeploy 4.0 MSI for any reason, the recommended way is to install the free Visual Studio Community SKU from //visualstudio.microsoft.com/vs/community/ and get the MSI from the Visual Studio's package cache. The package cache is under %programdata%\microsoft\visualstudio\packages and you should see folders starting with the 'Microsoft.VisualStudio.WebDeploy.Msi'.

**Comment by NeskireDK** [comment]
Roger that, I suppose target framework has no real impact on Web deploys ability to deploy asp.net 4.8 with either version.
On 2 Dec 2019, at 23.00, Baris Caglar <notifications@github.com> wrote:

﻿

The comment I got from the engineer who upgraded Web Deploy to 4.0 is this:

"The biggest change from v3.6 to v4.0 is the change of the target framework: .NET v3.5 to v4.5. Other than that, there are bug fixes that don’t impact the end users directly".

**Comment by sujitnayak** [comment]
@NeskireDK that is correct.

**Comment by Almas1997** [comment]
I discovered a major change in Web Deploy 4.0 in contrast to 3.6.

WD 3.6 installation procedure doesn't create WPDeploy* users and doesn't create rules for Management Service Delegation on Windows Server 2019 (1809), so I couldn't use deployment with non-administrator accounts.

But it works fine on previous versions of Windows Server (2012/2016).

So 4.0 is better for WS2019

See https://forums.iis.net/t/1250176.aspx?Web+Deploy+3+6+on+Windows+Server+2019+usage+issue

**Comment by neddus** [comment]
> 
> 
> I discovered a major change in Web Deploy 4.0 in contrast to 3.6.
> 
> WD 3.6 installation procedure doesn't create WPDeploy* users and doesn't create rules for Management Service Delegation on Windows Server 2019 (1809), so I couldn't use deployment with non-administrator accounts.
> 
> But it works fine on previous versions of Windows Server (2012/2016).
> 
> So 4.0 is better for WS2019
> 
> See https://forums.iis.net/t/1250176.aspx?Web+Deploy+3+6+on+Windows+Server+2019+usage+issue

It could be that the minimum password length policy for local accounts is more than 12, what both WebDeploy 3.6 and 4.0 tries to use when installing, and failing silently to create accounts. I had to modify the powershell-script to create passwords meeting the new requirements on the new server.
