### ISSUE TITLE
Possible CPU throttling page improvement

### ISSUE THREAD

**Issue by lextm** [MicrosoftDocs/iis-docs#225]
This page talks about the settings,

https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-cpu-throttling-sand-boxing-sites-and-applications

but does not give a concrete example on how to simulate high CPU to test them out.

WCAT was mentioned, but generally speaking it is a bit of hard to use that to trigger exactly the level of CPU usage,

> That's it. Using a load generating tool, send requests to the Default Web Site. A tool such as WCAT can be used (https://www.iis.net/community/default.aspx?tabid=34&g=6&i=1467) to generate traffic.

I wrote a simple test page for this purpose,

https://blog.lextudio.com/a-test-page-for-iis-cpu-throttling-8813f76c67d

Will later create a pull request to list the steps of a typical setup and testing.

**Comment by shirhatti** [comment]
@lextm We appreciate the contribution to the IIS community, but we are concurrently trying to make the IIS docs as concise as possible. We think this content is better suited to live in a blog post instead.
