### ISSUE TITLE
Bad Request responded with 404.xx

### ISSUE THREAD

**Issue by ugurcemozturk** [MicrosoftDocs/iis-docs#269]
Hey,
I've found two strange behaviours of IIS. 

### Code Snippet

    <httpErrors existingResponse="PassThrough" />
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="5000000" />
        <verbs allowUnlisted="true">
          <add verb="HEAD" allowed="false" />
        </verbs>
      </requestFiltering>
    </security>

### Problem Description
In this code snippet, 

1. Rejects the request if content size is bigger than 5 MBs. It responds with a 404. (404.13)
2. Rejects the HTTP HEAD requests. It also responds with 404.

### Expected Behavior
Since HTTP Status Codes are independent of the running platform, we expected a common message, not the IIS specific status code. 

1. For request limits, It should respond with **400 - Bad Request.** 
 ![image](https://user-images.githubusercontent.com/6145239/48538876-aa1d0f80-e8c6-11e8-8e0b-26ada4ea189e.png)

2. For ignored HTTP Method, It should respond with **405 - Method Not Allowed.**
![image](https://user-images.githubusercontent.com/6145239/48538944-d6d12700-e8c6-11e8-8737-4419cf8fce18.png)

This default behaviour affects our SEO, security reports and proper communication with other services. 

### References

- Adding Verbs: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/verbs/add

- Request Limits: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/

- Standart HTTP Status Codes: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Kind Regards,
Ugur Cem.

**Comment by bariscaglar** [comment]
@ugurcemozturk thanks for reporting this. We will look into fixing it for the next version of IIS. Closing this issue here because this would be fixed in IIS code, not the documentation.

**Comment by ugurcemozturk** [comment]
Hey @bariscaglar,

I would like to contribute your work If it's possible. 

By the way, I couldn't found the exact place to report an issue/improvement for IIS, that's the main reason to put it under docs repository. If you have a platform to collect the issues, feel free to share with me.

Thanks for your fast reply,
Ugur Cem.

**Comment by bariscaglar** [comment]
> I would like to contribute your work If it's possible.
IIS code itself is part of Windows and therefore not open source, but thanks for the offer!

You can try iis.net forums for reporting issues as well as feedback hub in Windows. Reporting it here will also get it to us, and perhaps faster, but we will need to close the issue while we file it internally and there's no good mechanism to track it on your end, which is true for all ways of reporting.

**Comment by ugurcemozturk** [comment]
Hey @jhkimnew, 
`Considering IIS designed like that ` : I aggree with you but what I want to mention is, It seems like the current design won't follow the RFC Standars so not compatible with external systems.  
`Here is how to generate 400 response status code instead of 404.13.` It's an alternative way for WebApp but I am using REST API, no HTML or other stuff. All response are JSON formatted. (No static .aspx files)

By the way, this is a solution for WepApp for sure but wont cover all stories. So better to fix it on IIS side. I don't think that it is a good practice to customize global standarts.

Thanks a lot for your answer!
Cheers.

**Comment by ugurcemozturk** [comment]
@bariscaglar @jhkimnew 
Btw, as a -patch- (not the solution), It may be fixed by using Kestrel and IIS both. Kestrel is responding with exact correct status codes and can be used as a reverse proxy via IIS.
