### ISSUE TITLE
Using the URL Rewrite Module - Update download link

### ISSUE THREAD

**Issue by CometstarMH** [MicrosoftDocs/iis-docs#305]
Hi all,

The download links for the URL Rewrite modules seem to be pointing to the version released in 2010, which cannot be installed in Windows Server 2016 without some registry hacks. 
[https://stackoverflow.com/a/35319943/10960531](url)

There is actually a newer version in 2015 as in here [https://www.microsoft.com/en-us/download/details.aspx?id=47337](url), which works without the hacks. Should the links be updated to point to this version?

BTW, the page is /iis/extensions/url-rewrite-module/using-the-url-rewrite-module.md

**Comment by shirhatti** [comment]
Thanks for catching that! Here's the most up to date page-https://www.iis.net/downloads/microsoft/url-rewrite

I'll update the docs to reflect that
