### ISSUE TITLE
"New Features Introduced in IIS 10.0, version 1809" documentation never published?

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/iis-docs#419]
https://docs.microsoft.com/en-us/iis/ still redirects to the "Version 1709" article. 

However, there appears to be a newer article for v1809 here: 

https://github.com/MicrosoftDocs/iis-docs/blob/6232350988433355e241824a0c5a64f991b54490/iis/get-started/whats-new-in-iis-10-version-1809/new-features-introduced-in-iis-10-1809.md

There is also a corresponding pull request: https://github.com/MicrosoftDocs/iis-docs/pull/215

Was the newer article ever published, and if so why doesn't the link redirect to it?

**Comment by SebastienAndre** [comment]
Hi @jeffreymcclain 
Do you plan to update https://docs.microsoft.com/en-us/iis/ with version 1809 for Windows Server 2019?
Thanks

**Comment by Rick-Anderson** [comment]
Live now
https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1809/new-features-introduced-in-iis-10-1809

**Comment by jeffreymcclain** [comment]
@Rick-Anderson Thanks, also do you think it'd make sense to add documentation for more recent versions of this service as well (e.g. if there were any changes for the Windows Server 2022 and/or Windows 11 releases)?

I think my original issue report was based on the latest version of the software way back in 2019, but I'm guessing there have been one or more releases since then, so it might be worth someone at Microsoft adding those to the documentation those as well.

**Comment by jeffreymcclain** [comment]
Also on a lighter note, I thought the timeline of the responses on this issue report was kinda funny (wasn't an urgent issue at all, I'd pretty much forgotten about it): https://tenor.com/view/its-been-a-crazy-couple-years-insane-its-been-a-crazy-years-crazy-years-audrina-patridge-gif-14474909

**Comment by Rick-Anderson** [comment]
Although I work for MS I'm doing this a volunteer and I haven't worked on IIS for a decade so I have no idea what's current. If you can send me links to updates I'll try to get that published.
