### ISSUE TITLE
Missing nuget dependency for Microsoft.Web.Administration to System.Reflection.TypeExtensions

### ISSUE THREAD

**Issue by KevM** [MicrosoftDocs/iis-docs#479]
I am seeing this problem with the most recent release nuget `Microsoft.Web.Administration 11.1.0`. It looks like there is a missing dependency to an assembly which is loaded via reflection. `System.Reflection.TypeExtensions, Version=4.1.0.0`. For my use case adding a reference to [this exact nuget version] (https://www.nuget.org/packages/System.Reflection.TypeExtensions/4.1.0) solved the issue.

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.   File name: 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'           at Microsoft.Web.Administration.ConfigurationElement.CreateStronglyTypedWrapper(Type elementType)                       
at Microsoft.Web.Administration.ConfigurationElement.GetCollection(Type collectionType)                                 
at Microsoft.Web.Administration.Site.ApplicationCollectionCreator()                                                     
at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)                    
at Microsoft.Web.Administration.Site.get_Applications() 
```
> Not sure where to report this issue as there is no obvious repo linked to this Nuget:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef882d6-10fa-1f34-3942-2f4c4c5a657b
* Version Independent ID: 3552ef90-1171-037d-c1ad-53688203bab4
* Content: [Microsoft.Web.Administration Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration?redirectedfrom=MSDN&view=iis-dotnet#feedback)
* Content Source: [iis-dotnet/xml/ns-Microsoft.Web.Administration.xml](https://github.com/MicrosoftDocs/iis-dotnet-sdk-docs-pr/blob/live/iis-dotnet/xml/ns-Microsoft.Web.Administration.xml)
* Product: **iis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **soshir**

**Comment by lextm** [comment]
IMHO the sole valid usage of that NuGet package should be IIS Administration API, https://github.com/microsoft/IIS.Administration

You might stick to the assembly shipped with full IIS on your machine instead.

**Comment by KevM** [comment]
I think this was related to a weird problem where mixing .net standard projects with .net framework asp.net pre sdk style .csproj format was not seeing transitive dependencies copied into output directories.
