### ISSUE TITLE
PIFF download link is 404

### ISSUE THREAD

**Issue by sandersaares** [MicrosoftDocs/iis-docs#498]
The download link on this page is a 404: https://github.com/MicrosoftDocs/iis-docs/blob/master/iis/media/smooth-streaming/protected-interoperable-file-format.md

**Comment by lextm** [comment]
The entire IIS Media Services seems to be obsolete now due to IIS 8.x end of life. Its installer and other bits have been removed from Microsoft Downloads.

**Comment by 3052** [comment]
I dont think just deleting this page, which that PR seems to do:
https://github.com/MicrosoftDocs/iis-docs/pull/1017/files#diff-62f501eea4900f57739913d662de322c6f722f1a62b1282b3d4a68164497a32f

is the correct action here. the PIFF spec is a valid spec that is still being used as of today, by providers such as https://hulu.com and countless others. at a minimum that document should be moved somewhere else and kept publicly available

**Comment by 3052** [comment]
looks like here:
https://github.com/MicrosoftDocs/iis-docs/commit/001db77fa6b05f23a2af75fddd226bff99839ee1

the URL was changed from:
https://go.microsoft.com/?linkid=9682897

to just link back to itself. by @kturetz and @wadepickett. the previous URL redirected to here:
https://download.microsoft.com/download/4/3/D/43D2D2B7-F101-4463-ACA1-548A1F21D57C/Protected Interoperable File Format (PIFF) 1.1.pdf

I found a copy here:
https://github.com/heksesang/bmff/blob/master/MatrixIO.IO.Bmff/Specifications/Protected Interoperable File Format (PIFF) 1.1.pdf

this should be a publicly available standard, hosted by Microsoft itself. people should have to go hunting for it across the internet.

**Comment by Rick-Anderson** [comment]
Fixed by #1017

**Comment by 3052** [comment]
https://github.com/MicrosoftDocs/iis-docs/issues/1027

**Comment by 3052** [comment]
@Rick-Anderson no, its definitely is not.
