### ISSUE TITLE
Author info appears at both the beginning and end of the article

### ISSUE THREAD

**Issue by shirhatti** [MicrosoftDocs/iis-docs#5]
I noticed https://github.com/MicrosoftDocs/iis-docs/blob/master/iis/get-started/whats-new-in-iis-10/http2-on-iis.md has author information at the beginning and end of the articles.
I suspect this may occur in additional articles that I haven't yet discovered.

We can this issue to track such articles that need cleaning up.

- [ ] https://github.com/MicrosoftDocs/iis-docs/blob/master/iis/get-started/whats-new-in-iis-10/http2-on-iis.md

**Comment by atomissariyaporn** [comment]
Gets

**Comment by bariscaglar** [comment]
@shirhatti I don't see why this should be a problem. I suggest we close this if you're not feeling to strongly about it.

**Comment by bariscaglar** [comment]
@shirhatti reactivate if you think this is really important.
