### ISSUE TITLE
IIS enable rebind feature doesnt work at all!!

### ISSUE THREAD

**Issue by kriti218** [MicrosoftDocs/iis-docs#503]
We have on-premise VMs running with IIS 10 version. I tried enabling rebind feature on one of the VMs and installed renewed version of SSL certificate on VM, but the new SSL cert never got binded with web site SSL binding.
I am really disappointed as i followed what is given in document and installing new version of SSL cert is not getted binded.

**Comment by lextm** [comment]
A feature like that involves several Windows components, so learning what's wrong on that specific machine requires direct access.

You should contact Microsoft support team via http://support.microsoft.com if you are sure the the steps from the documentation have been followed.
