### ISSUE TITLE
SslMapCert

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/iis-docs#523]
At https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/access , the documentation for the SslMapCert value of the sslFlags attribute is unclear at best. 

First, SslMapCert is mentioned is Configuration section but not the Overview section, whereas all other values are mentioned in the overview section.

Second, is SslMapCert really a valid value? I do not see it in IIS_schema.xml.

Thirdly, if the Ssl128 value is used, does it prevent the use of 256-bit TLS encryption or is it only 128-bit or higher?

Fourthly, if the SslRequireCert value is used, does the SslNegotiateCert value also need to be used?

Fifthly, how does the SslMapCert value interact with client certificate authentication settings specified in the authentication setting?

Please fix these issues.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/

**Comment by rossmpersonal** [comment]
Lack of resources is not a valid reason to close an issue. Lack of resources is a valid reason for not resolving an issue as fast as would be ideal.
