### ISSUE TITLE
appcmd coomand for setting failure definitions in documentation is not working

### ISSUE THREAD

**Issue by itahirov** [MicrosoftDocs/iis-docs#539]
https://docs.microsoft.com/en-us/iis/troubleshoot/using-failed-request-tracing/using-failed-request-tracing-rules-to-troubleshoot-application-request-routing-arr?source=docs#to-configure-failed-request-tracing-rules-using-the-command-line

./appcmd.exe set config "Default Web Site" -section:system.webServer/tracing/traceFailedRequests /[path='*'].failureDefinitions.statusCodes:"200-399"

**_ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', or '@N' where N is a numeric index into the collection. )_**

not sure how it has to be formatted and generally there are no files generating in \inetpub\logs\FailedReqLogFiles\ logs directory.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
