### ISSUE TITLE
Inadequete information

### ISSUE THREAD

**Issue by bobsort** [MicrosoftDocs/iis-docs#555]
[Enter feedback here]

detail for collectionName and collectionType is not adequate. 
for example if I'm trying to ONLY read "system.webServer/handlers"  section of web.config of current application what should I pass to it? what are valid content of that string? can I pass name of USA presidents as string to it?

collectionType is linked to System.types which is correct, but if I pass for example System.String to it, would it convert the whole section to string and return it to me? what are the valid types.

It seems the behavior of this class is changed too, it returns the whole section of handlers regardless of their location. I am getting list of configuration from GetWebConfiguration(site_name, app_path) which app_path and site_name refer to my current application location. but the list I receive includes all the configuration in system including those that is stored in machine and server level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b72b929-974a-fca2-8c10-933fa17d63e4
* Version Independent ID: 3e8c2819-349e-a746-5c61-d1978b9f12db
* Content: [ConfigurationElement.GetCollection Method (Microsoft.Web.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.configurationelement.getcollection?view=iis-dotnet)
* Content Source: [iis-dotnet/xml/Microsoft.Web.Administration/ConfigurationElement.xml](https://github.com/MicrosoftDocs/iis-dotnet-sdk-docs-pr/blob/live/iis-dotnet/xml/Microsoft.Web.Administration/ConfigurationElement.xml)
* Product: **iis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **soshir**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean.
