### ISSUE TITLE
IIS Advanced Logging download links are broken

### ISSUE THREAD

**Issue by mitchclarkebase2** [MicrosoftDocs/iis-docs#559]
The links in the middle of the page (iis/extensions/advanced-logging-module/advanced-logging-readme.md) for downloading the Windows Installer files both no longer exist (https://go.microsoft.com/?linkid=9689912 and https://go.microsoft.com/?linkid=9689913). 

Are these msis no longer available? I have tried finding them on the official site and have ended up with the same result. I know for certain that they were available at this address on March 29th (https://download.microsoft.com/download/9/6/5/96594C39-9918-466C-AFE0-920737351987/AdvancedLogging64.msi), so they must have been removed in the last month.

If they are available can you please supply me with new links to download the 64-bit one from? Once I am able to download it I will store it myself to prevent this issue in the future.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/iis/extensions/advanced-logging-module/advanced-logging-readme

**Comment by Rick-Anderson** [comment]
The IS Advanced Logging is an extension for Internet Information Services (IIS) 7 is no longer available. We recommend [Enhanced Logging for IIS 8.5](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-85/enhanced-logging-for-iis85).
