### ISSUE TITLE
url rewrite use camel case?

### ISSUE THREAD

**Issue by vchy1997** [MicrosoftDocs/iis-docs#566]
**resource code use ToLower case:**
https://github.com/dotnet/aspnetcore/blob/07c6a62587fb147cefbd5f84c5a308b5e087cb9c/src/Middleware/Rewrite/src/IISUrlRewrite/InputParser.cs#L113-L126

**doc use tolower** 
https://github.com/MicrosoftDocs/iis-docs/blob/24715c577b556128b10bc3d0d0e34912e9aed741/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference/samples/sample8.xml#L8

Is this a mistake?

**Comment by wadepickett** [comment]
@vchy1997 , thanks very much for pointing out this issue, and providing the fix.

**Comment by vchy1997** [comment]
@wadepickett ，thank you very much for checking this issue
