### ISSUE TITLE
Are tags in the IIS configuration case sensitive? If yes, there is a mistake in the docs

### ISSUE THREAD

**Issue by ioah86** [MicrosoftDocs/iis-docs#580]
I couldn't find a reference if tags inside the Microsoft IIS configuration files are case sensitive or not.
However, after asking in [StackOverflow](https://stackoverflow.com/questions/68353311/are-microsoft-iis-configuration-tags-case-sensitive/68353702?noredirect=1), it turns out that they are.

In this case, the sample [here](https://github.com/MicrosoftDocs/iis-docs/blob/main/iis/configuration/system.ftpServer/security/authentication/index/samples/sample1.xml) contains a mistake by uppercasing the tag `Authentication`.

**Comment by vchy1997** [comment]
@ioah86  Hi . 
Maybe you can check the basic configuration of the local xml file:

%WinDir%\System32\Inetsrv\config\schema\Ftp_schema.xml

Line 296 clearly states <element name="authentication">

and so. This may be a typo

![iis](https://user-images.githubusercontent.com/53808804/125731390-1e27a525-0855-4634-9d02-bd3a28809ff9.png)

**Comment by ioah86** [comment]
I see a fix has been done. I will close this issue.
