### ISSUE TITLE
Web Deploy download page should update OS it supports

### ISSUE THREAD

**Issue by adamkimsft** [MicrosoftDocs/iis-docs#582]
The supported operating system section at https://www.microsoft.com/en-us/download/details.aspx?id=43717 perhaps should list newer OS (such as Server 2016 and 2019) since the tool shows it supports IIS 10 (https://www.iis.net/downloads/microsoft/web-deploy) and the newer systems have IIS 10.

**Comment by shirhatti** [comment]
I've updated the link at https://www.microsoft.com/en-us/download/details.aspx?id=43717
