### ISSUE TITLE
Remove empty block

### ISSUE THREAD

**Issue by rliuup** [MicrosoftDocs/iis-docs#589]
[Enter feedback here]

Remove this block.

![image](https://user-images.githubusercontent.com/76539124/139912368-660ecec2-3b83-4ab0-8986-ed6ce3b9415e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed2ac62-395a-b945-f922-95afbf2ab10b
* Version Independent ID: e5e56aaa-a0d1-14f5-4924-0d938173e7b1
* Content: [SiteCollection.Add Method (Microsoft.Web.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.sitecollection.add?view=iis-dotnet#Microsoft_Web_Administration_SiteCollection_Add_System_String_System_String_System_String_System_String_)
* Content Source: [iis-dotnet/xml/Microsoft.Web.Administration/SiteCollection.xml](https://github.com/MicrosoftDocs/iis-dotnet-sdk-docs-pr/blob/live/iis-dotnet/xml/Microsoft.Web.Administration/SiteCollection.xml)
* Product: **iis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **soshir**

**Comment by Rick-Anderson** [comment]
@gewarren  do you know how to fix that snippet. It looks like a snippet is split in 3

**Comment by gewarren** [comment]
Yes, they are piecing together 3 different snippets from this file: https://github.com/MicrosoftDocs/iis-dotnet-sdk-docs-pr/blob/live/iis-dotnet/snippets/csharp/IIS/IIS/Microsoft.Web.Administration.Site/CS/Microsoft.Web.Administration.Site.cs. It's silly.  I'd suggest adding a new .cs file with just the code you want to display.

The other weird thing is that the parameter types are pointing to MSDN. That should be fixed...I'll investigate.

**Comment by Rick-Anderson** [comment]
Fixed in #10
