### ISSUE TITLE
Create a doc for the new IIS HSTS feature

### ISSUE THREAD

**Issue by bangbingsyb** [MicrosoftDocs/iis-docs#62]
I plan to draft a doc for the new IIS HSTS feature we added into RS3 that will be released soon.

**Comment by shirhatti** [comment]
Merged in 1d7a3666a288c8b6a00b50f1d5b49a3f570401dd

**Comment by sundarchi1** [comment]
Is this new feature smart enough to **not** redirect localhost Application Initialization requests?

https://support.microsoft.com/en-us/help/2843964/application-initialization-module-fails-when-web-site-requires-ssl

The workaround there works, but if you are internally implementing a URL rewrite that we will not be able to configure (when `redirectHttpToHttps` is true) then please make sure to negate the 2 IIS warmup user agents:

User Agent 1: IIS Application Initialization Warmup
User Agent 2: IIS Application Initialization Preload

**Comment by sundarchi1** [comment]
@bangbingsyb @shirhatti ^

**Comment by bangbingsyb** [comment]
Sorry for my delayed response. Good question and interesting scenario. I want to clarify that the redirectHttpToHttps knob for HSTS feature is NOT an internal URL rewrite. What it does is parse the original requested URL, and put the https version of the requested URL in the location response header, and return 301 with no response body. There is not internal rewrite to make IIS treat an HTTP request as an HTTPS request. So I don't think it should not break App Initialization.
