### ISSUE TITLE
removeServerHeader Bug

### ISSUE THREAD

**Issue by sundarchi1** [MicrosoftDocs/iis-docs#76]
The new removeServerHeader boolean property added in IIS 10 does not work for the very first request to a web application. If you fresh start/restart a web application with this property set in its web.config, and then send a fresh GET request to a page on the site, the Server header is still there. In subsequent requests, it is gone, as it should be.

Definitely seems like a bug. If it's not, then please amend this documentation letting people know.

**Comment by bangbingsyb** [comment]
This is a known issue, and we have fixed it in the upcoming (Oct 2017) IIS10 RS3 release. Thanks for letting us know your concern.

**Comment by sundarchi1** [comment]
Oh, great!

You can't get this in one of those cumulative updates for Windows every month? You guys aren't releasing a Desktop Experience version of Windows Server RS3, which basically means we won't see this fix until the next full release )-:

**Comment by bangbingsyb** [comment]
Windows Server Core edition will be the server SKU released in RS3, but not full server with UI. So you can still see the fix if you use server core (besides UI, they are the same), plus we will release some new features in RS3, e.g. native HSTS support. It is ashamed that this little feature does not work well out of box for IIS10. The current workaround is to use URL Rewrite to blank the server header if you really want to hide this piece of information. Unfortunately, the fix does not meet the bar of Windows update.

**Comment by sundarchi1** [comment]
I know - hopefully you will change your mind and release semi-annual with UI. Kind of dumb to leave it out, we cannot use Core because it does not meet our needs.

Appreciate the quick replies & looking forward to hearing more about the new features!

**Comment by bangbingsyb** [comment]
> I know - hopefully you will change your mind and release semi-annual with UI. Kind of dumb to leave it out, we cannot use Core because it does not meet our needs.
> 
> Appreciate the quick replies & looking forward to hearing more about the new features!

Good news:

The fix for this issue was released in the 2019.1C patch (the 3rd week of Jan 2019) to Windows Server 2016 1607.
