### ISSUE TITLE
Broken Documentation Link

### ISSUE THREAD

**Issue by sundarchi1** [MicrosoftDocs/iis-docs#79]
See below for a help link that seems to redirect to an internal Microsoft staging website instead of the real Technet page. This is IIS 10.

![capture](https://user-images.githubusercontent.com/31782486/30791815-4c181fc8-a183-11e7-89da-8e703157c9b1.PNG)

**Comment by sundarchi1** [comment]
Also on "Edit Request Filtering Settings" (Edit Feature Settings) dialog box, that has invalid link too.

**Comment by terrimorton** [comment]
This is a product issue, not a documentation issue. @shirhatti can you take point on this?

**Comment by sundarchi1** [comment]
Surprised this is still open, any fix yet?

**Comment by terrimorton** [comment]
The English link in IIS Manager has been updated, and the other locales are still being worked on.

**Comment by rmcmurray** [comment]
Hi @sundarchi1 - I apologize, this took a little longer than expected to rectify; there were a lot of language-specific fwlinks that needed to be found and updated.

@shirhatti - I believe that all of the fwlinks for this section of the UI have been fixed; you can run a test pass to double-check.

**Comment by bariscaglar** [comment]
@shirhatti do we have a confirmation that these are fixed?

**Comment by shirhatti** [comment]
Verified that these are fixed
