### ISSUE TITLE
"What's new in IIS 10 RS3" missing from docs

### ISSUE THREAD

**Issue by sundarchi1** [MicrosoftDocs/iis-docs#87]
It's missing from here:
https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/new-features-introduced-in-iis-10

Please mention things like the [removeServerHeader bug fix](https://github.com/MicrosoftDocs/iis-docs/issues/76) and Brotli compression (couldn't find out how to enable - perhaps @shirhatti can help?)

**Comment by shirhatti** [comment]
Fixed in 4004ce5042833265cad058012f0fa1bd192b4453

**Comment by EatonZ** [comment]
@shirhatti I'm confused about the Logging Enhancements. I added them to my non-1709 IIS 10 install and they work, so they definitely are not 1709 exclusive. I believe that entry should be removed.

**Comment by shirhatti** [comment]
You are correct in your observation.

These enhancements were introduced in 1709 but have since been backported to [Server 2016](https://support.microsoft.com/en-us/help/4025334/windows-10-update-kb4025334) and [Server 2012 R2](https://support.microsoft.com/en-us/help/4025335/windows-8-1-windows-server-2012-r2-update-kb4025335).

**Comment by bangbingsyb** [comment]
Yes, the feature has been backported to WS2016 and WS2012R2 after its development in 1709.

This is a feature to provide web admins security-related telemetry data (log). As the push to deprecate less secure TLS protocol (e.g. TLS1.0), it is valuable to audit the actual protocol version and cipher suites used in the live traffic. Consider it will be a slow process for most customers migrate to WS2016 ver 1709 as well as the urgent need of such feature, we decide to backport it down to WS2012R2 (through Windows update).

**Comment by sundarchi1** [comment]
No RS4 docs?
Also, any preview docs for the upcoming RS5 Server 2019?

The insider build announcements have been devoid of any IIS news.
