### ISSUE TITLE
Incorrect display of code sample

### ISSUE THREAD

**Issue by DanAtkinson** [MicrosoftDocs/iis-docs#934]
The code sample appears to be broken into three separate snippets which makes it look odd:

![image](https://user-images.githubusercontent.com/23440/190140739-8ccafa0e-e3ba-4111-bd06-9064c97eb742.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97ea8e4-915f-9ab1-2a42-8008f56f88d4
* Version Independent ID: 46db91d9-11fa-174a-8199-b8c7a402e4b7
* Content: [Application.ApplicationPoolName Property (Microsoft.Web.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.application.applicationpoolname?redirectedfrom=MSDN&view=iis-dotnet#Microsoft_Web_Administration_Application_ApplicationPoolName)
* Content Source: [iis-dotnet/xml/Microsoft.Web.Administration/Application.xml](https://github.com/MicrosoftDocs/iis-dotnet-sdk-docs-pr/blob/live/iis-dotnet/xml/Microsoft.Web.Administration/Application.xml)
* Product: **iis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **soshir**

**Comment by Rick-Anderson** [comment]
I agree but we don't have the resources to fix that.
