### ISSUE TITLE
Is there a way to allow patterns or wildcards in requestFiltering/alwaysAllowedUrls?

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/iis-docs#938]
I found https://github.com/MicrosoftDocs/iis-docs/blob/main/iis/configuration/system.webServer/security/requestFiltering/alwaysAllowedUrls/index.md but it makes it not explicit whether patterns or wildcards can be used.

As more people have this question, it would be good if this could be made explicit in the docs.
If it is not possible - please explain what the recommended workaround is.

Also see https://stackoverflow.com/questions/25942653/can-you-use-iis-7-5-filtering-for-alwaysallowurls-with-a-wildcard-or-pattern.

**Comment by lextm** [comment]
I just posted an answer there. In short, people should have migrated to URL Rewrite module (released a long while ago) for that.

**Comment by hansmbakker** [comment]
@Rick-Anderson @lextm please note that Azure App Service on Windows seems to still require this to fix urls. E.g. if you have an existing application that requires the word `bin` in the URL, by default App Service blocks that, but you can use `web.config` to allow it again using `alwaysAllowedUrls` or `hiddenSegments`.

`hiddenSegments` is not preferred because then it allows `bin` in all URLs rather than specific URLs with a wildcard.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>

	<!-- To customize the generated asp.net core module settings see https://go.microsoft.com/fwlink/?linkid=838655 -->

	<system.webServer>
		<security>
			<!-- Taming or application X -->
			<requestFiltering allowDoubleEscaping="true">
				<!-- allowDoubleEscaping="true" is needed for some GIFs that have a + in their name -->
				<!-- 
				  The word "bin" is not allowed by IIS but application X.
				  We used alwaysAllowedUrls but that does not allow wildcards so we opted for removing it
				  from hiddenSegments, since we do not know the full list of URLs that application X has with 'bin'
				  https://stackoverflow.com/questions/25942653/can-you-use-iis-7-5-filtering-for-alwaysallowurls-with-a-wildcard-or-pattern
				-->
				<hiddenSegments>
					<remove segment="bin" />
				</hiddenSegments>
				<requestLimits maxQueryString="25000" />
			</requestFiltering>
		</security>
	</system.webServer>
</configuration>
```
