### ISSUE TITLE
system.web Docs

### ISSUE THREAD

**Issue by sundarchi1** [MicrosoftDocs/iis-docs#94]
Can we get some system.web docs? It's really hard to find updated documentation for all elements in there - they are mostly outdated MSDN pages.

Please add system.web to the configuration reference:
https://docs.microsoft.com/en-us/iis/configuration/

**Comment by shirhatti** [comment]
@honggit @csharpfritz Thoughts?

**Comment by csharpfritz** [comment]
There is extensive documentation about ASP.NET available at: https://github.com/aspnet/Docs/tree/master/aspnet and they're on the docs site at: https://docs.microsoft.com/en-us/aspnet/overview

**Comment by sundarchi1** [comment]
I think it would still be useful to have an expandable tree view like on IIS.net to easily see and explore all settings.

**Comment by csharpfritz** [comment]
Both websites use the same web UI framework on docs.microsoft.com.



Jeff
