### ISSUE TITLE
WDS Configure Required Permissions links are all broken

### ISSUE THREAD

**Issue by csharmath** [MicrosoftDocs/iis-docs#96]
All links are broken mentioned at WDS permissions section

https://docs.microsoft.com/en-us/iis/web-hosting/installing-infrastructure-components/preparation-activities-for-wds#configure-required-permissions

They link to technet2.microsoft.com which says it's has been removed.

Microsoft docs guys, oh my! Can't you guys bing crawl your own sites and figure out if you have dead links ? Or before removing contents, make sure that they are not linked on your own docs site ?

Also, why is this page using the iis-docs ? that's weird
Is someone mixing up IIS the webserver with Infrastructure Installation Services, like WDS ?

**Comment by dend** [comment]
Thank you for the feedback, we are working on addressing this!

**Comment by dend** [comment]
Current PR that fixes this:
https://github.com/MicrosoftDocs/iis-docs/pull/97

Given that links point to outdated documentation, we are removing them.

**Comment by csharmath** [comment]
So no fixed links to the docs, just removing them ? 
Weren't there anything useful on those original links explaining the required permissions ?

The whole point for me was to figure out what permissions do I need to grant to a gMSA account so that I can create a PowerShell JEA endpoint for non-admins to perform some basic tasks like changing WDS to stop answering clients, etc.
Would love to get some help on the required privileges for these actions

Thanks!

**Comment by csharmath** [comment]
Just in case someone else is reading this and wondering about the WDS permissions.

I had to grant full control to the computer account to it's own AD object's IntellimirrorSCP attribute, so I can use JEA with gMSA to enable/disable WDS.

**Comment by shirhatti** [comment]
@csharmath https://web.archive.org/web/20111228083854/http:/technet.microsoft.com/en-US/library/4aca2aae-a9cf-4b5c-afb2-573603cf77b0.aspx
