### ISSUE TITLE
Microsoft Learn should state that IIS 10.0 is latest version and not IIS 7.5

### ISSUE THREAD

**Issue by Heer-Boaz** [MicrosoftDocs/iis-docs#993]
The page `iis/extensions/introduction-to-iis-express/iis-express-overview.md` incorrectly states that:

> "The most current version of the product is IIS 7.5 Express"

Also, it provides outdated information like:

> "IIS Express is automatically included with [WebMatrix](https://www.microsoft.com/web/webmatrix "Microsoft WebMatrix"), a new and complete tool that greatly simplifies web development. Visual Studio 2010 SP1 allows IIS Express used as the web server instead of Cassini. You can also manually configure Visual Studio 2008"

I would edit the document myself, but am unsure about what to do with the outdated information, such that it doesn't require frequent updates just to keep it fresh.

**Comment by lextm** [comment]
Duplicate to #983

**Comment by Heer-Boaz** [comment]
> Duplicate to #983

Will close this issue, as it is an exact duplicate.
