### ISSUE TITLE
Link to IIS Log Cleaner doesn't work

### ISSUE THREAD

**Issue by funkysi1701** [MicrosoftDocs/iis-docs#995]
on this page there is a link to http://www.erezbenari.com/apps/IISLogCleaner.exe however this is a dead link and throws an error

iis/manage/provisioning-and-managing-iis/managing-iis-log-file-storage.md

Either replace the link with a working one or remove

**Comment by lextm** [comment]
The PR has been merged, so you can verify and close this issue.

**Comment by funkysi1701** [comment]
Thank you for sorting this
